### ISSUE TITLE
Talk about github!

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/final_presentation#38]
Somewhere in the presentation we should mention that all code/process is available to view on github, and point out that we're at github.com/routelandia

**Comment by joshproehl** [comment]
Probably wouldn't hurt to mention Slack as well...

**Comment by pgicking** [comment]
I think it should be in the "tools used" section if we mention it, or somehow jesse could work it into the conclusion?

**Comment by joshproehl** [comment]
We did it, it's done. :-)
