### ISSUE TITLE
security vulnerabilities

### ISSUE THREAD

**Issue by kristinann** [PSU-Capstone-2014-B/final_presentation#39]
Hey All - 

Not sure how to get in touch with you all, I'll see if this works. 

Hope everything is well with you all.

I got notified that this repo has security vulnerabilities - can we archive this repo somehow?

Thanks!!

Kristin

**Comment by joshproehl** [comment]
Hey Kristin, good to hear from you!

As far as this repo, as well as the other presentation repo, the security "vulnerabilities" reported really don't matter. It's only a presentation for one, and it's not live anywhere. :-)
In any case, the vulnerabilities are in another project that this code uses to build itself, and so would not impact any users viewing this code even if it were deployed anywhere to be viewed.

I've gone ahead and marked both the announcement presentation project and this final presentation project as "no longer maintained", so I believe we won't be bothered by any further notifications!

**Comment by kristinann** [comment]
Josh - Great to hear from you. Thank you! I suspected that it wasn't a big deal, but wasn't quite sure how to solve the issue. Thank you for taking care of it!

Kristin
